### ISSUE TITLE
Add checks for missing maven plugins

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/project-keeper-maven-plugin#60] opened 2021-01-13 14:24 UTC
We need to check the following plugins:

maven-source-plugin
maven-javadoc-plugin

Both plugins are needed with Maven Release

**Comment by jakobbraun** [comment] 2021-01-14 14:49
duplicate of https://github.com/exasol/project-keeper-maven-plugin/issues/18

**Closed by jakobbraun** 2021-01-14 14:49 UTC
Labels: feature
